In [1]:
import torch
import numpy as np
torch.cuda.is_available()

False

ДЗ 1

In [2]:
class Neuron(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.fc = torch.nn.Linear(in_features=1, out_features=1)

  def forward(self, x):
    return torch.heaviside(self.fc(x), torch.tensor([0.0]))

In [3]:
neuron = Neuron()
neuron.fc.weight, neuron.fc.bias

(Parameter containing:
 tensor([[-0.1672]], requires_grad=True), Parameter containing:
 tensor([-0.2944], requires_grad=True))

In [4]:
neuron.fc.weight.data = torch.tensor([[1.0]])
neuron.fc.bias.data = torch.tensor([0.0])

In [5]:
x1 = torch.tensor([0.0])
x2 = torch.tensor([0.0])
neuron(-1.5 + neuron(x1 + x2 -0.5) + neuron((-x1 -x2 +1.5)))

tensor([0.], grad_fn=<NotImplemented>)

ДЗ 3

In [6]:
#a = torch.randn(int(10e8*3), dtype = torch.float32)
#print(a.dtype) # 10e8*3 < a < 10e8*4 float32

#b = torch.randn(int(10e8*1.5), dtype = torch.float64) 
#print(b.dtype) # 10e8*1.5 < b < 10e8*2 float64

#c = torch.randn(int(10e8*6), dtype = torch.float16) 
#print(c.dtype) # 10e8*6 < c < 10e8*7 float16

#d = torch.randint(3, 10, (int(10e8*8), 1), dtype = torch.int32)
#print(d.dtype) # 10e8*8 < d < 10e8*8.5 int32

#e = torch.randint(3, 10, (int(10e8*1.5), 1), dtype = torch.int64)
#print(d.dtype) # 10e8*1.5 < e < 10e8*2 int64



ДЗ 4

In [8]:
q = torch.randn(int(10e15), dtype = torch.float64) #даже не попробует выделить память
p = torch.randn(int(10e10), dtype = torch.float64) #будет выделять память пока она не заполнится и перезапустится

RuntimeError: ignored

ДЗ 5

In [2]:
x = torch.randn(int(200), int(10e4))
linear = torch.nn.Linear(int(10e4), int(10e3*3))

In [4]:
out = linear(x)
out.shape
#создалась матрица, на память, вроде как, никак не повлияло

torch.Size([200, 30000])